[package]
name = "mdbook-generate-summary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.21"
mdbook = "0.4.42"
serde = "1.0.215"
serde_json = "1.0.133"
